[tool.poetry]
name = "skyline"
version = "0.1.0"
description = ""
authors = ["Simon Myhre <simon@sqhead.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
